version: "3.4"

services:
  appdiabetes:
    image: appdiabetes
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8080:80
